---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker-deploy
spec:
  replicas: 2 # Number of pods to run
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
      - name: locust-worker
        image: locustio/locust # Replace with your Docker image name
        args: ["-f", "$(TEST_CASE)", "--worker", "--master-host", "locust-master.default.svc.cluster.local"]
        ports:
        - containerPort: 8089 # Replace with your application's port
        volumeMounts:
        - name: kafka-auth
          mountPath: /test/kafka-auth # Mount path inside the container
        - name: locust-tasks
          mountPath: /test/locust-tasks
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "daisy-kafka-kafka-bootstrap.kafka.svc.cluster.local:9093"
          - name: KAFKA_TOPIC
            value: "demo-topic"
          - name: KAFKA_SECURITY_PROTOCAL
            value: "SSL"
          - name: KAFKA_CA_LOCATION
            value: "/test/kafka-auth/ca.crt"
          - name: KAFKA_CERT_LOCATION
            value: "/test/kafka-auth/user.crt"
          - name: KAFKA_KEY_LOCATION
            value: "/test/kafka-auth/user.key"
          - name: KAFKA_BATCH_SIZE
            value: "65536"
          - name: TEST_CASE
            value: "/test/locust-tasks/exp3.py"
      volumes:
      - name: kafka-auth
        configMap:
          name: kafka-auth
      - name: locust-tasks
        configMap:
          name: locust-tasks